// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fraud.Models.Car
{
    public partial class BdD2FranshizViewModel
    {
        public int Id { get; set; }
        public int PrvId { get; set; }
        public int? PrvNo { get; set; }
        public string PrvDate { get; set; }
        public DateTime? PrvDateMiladi { get; set; }
        public int PolicyId { get; set; }
        public int? Bno { get; set; }
        public int ElhNo { get; set; }
        public string VsodurDate { get; set; }
        public DateTime? VsodurDateMiladi { get; set; }
        public string GovahiSodurDate { get; set; }
        public DateTime? GovahiSodurDateMiladi { get; set; }
        public int? Tafavot { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Nationalcode { get; set; }
        public string CompanyCode { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int BnSodurId { get; set; }
        public string BnSodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int PrvSodurId { get; set; }
        public string PrvSodurName { get; set; }
        public int BnUserId { get; set; }
        public string BnUserName { get; set; }
        public int PrvUserId { get; set; }
        public string PrvUserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public DateTime CreateDate { get; set; }
    }
}