// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fraud.Models.Car
{
    public partial class BdD6DayDamageViewModel
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int? Bno { get; set; }
        public int PrvId { get; set; }
        public int? PrvNo { get; set; }
        public string BnsodurDate { get; set; }
        public DateTime? SodurDateMiladi { get; set; }
        public string HadeseDate { get; set; }
        public DateTime? HadeseDateMiladi { get; set; }
        public int? DateDifference { get; set; }
        public string PrvDate { get; set; }
        public DateTime? PrvDateMiladi { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int SodurId { get; set; }
        public string SodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int? ElatHadese { get; set; }
        public string ElatHadeseName { get; set; }
        public int PrvSodurId { get; set; }
        public string PrvSodurName { get; set; }
        public int BnUserId { get; set; }
        public string BnUserName { get; set; }
        public int PrvUserId { get; set; }
        public string PrvUserName { get; set; }
        public string LastBnEndDate { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public DateTime CreateDate { get; set; }
    }
}