// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fraud.Models.Car
{
    public partial class BdP4TroubledCustomerViewModel
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int Bno { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int BnSodurId { get; set; }
        public string BnSodurName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public int PersonkindId { get; set; }
        public string PersonKindText { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CodeMelli { get; set; }
        public string CodePosti { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public DateTime? CreateDate { get; set; }
    }
}