// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fraud.Models.Car
{
    public partial class BdP5TroubledKhodroViewModel
    {
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int Bno { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int BnSodurId { get; set; }
        public string BnSodurName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public int KhodroId { get; set; }
        public string ShasiNo { get; set; }
        public string PelakNo { get; set; }
        public string Vin { get; set; }
        public string MotorNo { get; set; }
        public int? UserId { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public DateTime CreateDate { get; set; }
    }
}