// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fraud.Models.Car
{
    public partial class SalesP2AghsatGreater6ViewModel
    {
        public int Id { get; set; }
        public int? MaliBid { get; set; }
        public int PolicyId { get; set; }
        public int? Bno { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime? BnDateMiladi { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Nationalcode { get; set; }
        public string CompanyCode { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int BnSodurId { get; set; }
        public string BnSodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public string FvsodurDate { get; set; }
        public string SaresidDate { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public DateTime CreateDate { get; set; }
    }
}