// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities.Car
{
    [Table("DimSabegheSalesKind", Schema = "cr")]
    public partial class DimSabegheSalesKind
    {
        [Key]
        public int SabegheSalesKindId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public int? Sal { get; set; }
    }
}