// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities.Car
{
    [Table("SalesP7_SalSahkhtSanavatDiscount", Schema = "cr")]
    public partial class SalesP7SalSahkhtSanavatDiscount
    {
        [Key]
        public int Id { get; set; }
        public int PolicyId { get; set; }
        public int Bno { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime BnSodurDateMiladi { get; set; }
        public int SalSakhtMiladi { get; set; }
        public int SalSakhtShamsi { get; set; }
        public int TafavotSal { get; set; }
        public int? SabegheId { get; set; }
        public int? SabegheTypeId { get; set; }
        public string SabegheTypeName { get; set; }
        public int? Sal { get; set; }
        public string SabeghJaniName { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string Nationalcode { get; set; }
        public string CompanyCode { get; set; }
        public int AgentCode { get; set; }
        public string AgentName { get; set; }
        public int BnSodurId { get; set; }
        public string BnSodurName { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public DateTime CreateDate { get; set; }
    }
}