// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities.Car
{
   
    public partial class SP_PolicyPaginationResult
    {
        public int? PolicyId { get; set; }
        public int? BNo { get; set; }
        public int? ElhNo { get; set; }
        public int? ElhKindId { get; set; }
        public string ElhKindName { get; set; }
        public int? PrvId { get; set; }
        public int? PrvNo { get; set; }
        public int? HvId { get; set; }
        public int? HvNo { get; set; }
        public string BnSodurDate { get; set; }
        public string HadeseDate { get; set; }
        public int? DateDif { get; set; }
        public string ElamDate { get; set; }
        public string PrvDate { get; set; }
        public string HvDate { get; set; }
        public string DamageType { get; set; }
        public string ExtendedBNNo { get; set; }
        public int? ExtendedPolicyId { get; set; }
        public int? LastBimeCompanyId { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public int? CustomerId { get; set; }
        public string CustomerFName { get; set; }
        public string CustomerLName { get; set; }
        public int? AgentCode { get; set; }
        public string AgentName { get; set; }
        public int? SodurId { get; set; }
        public string SodurName { get; set; }
        public int? SalAdamKhesaratSarneshin { get; set; }
        public int? SalAdamKhesaratJani { get; set; }
        public int? SalAdamKhesaratMali { get; set; }
        public int? ElhChangeKindId { get; set; }
        public string ElhChangeKindName { get; set; }
        public int? ElhEllatId { get; set; }
        public string ElhElatName { get; set; }
        public decimal? BnPrmWithTax { get; set; }
        public decimal? BnPrmWithoutTax { get; set; }
        public decimal? Sandogh { get; set; }
    }
}
