// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Fraud.DB_Models
{
    public partial class ReportFromAllTable
    {
        public int Id { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public int KpiTypeId { get; set; }
        public string KpiTypeName { get; set; }
        public string Sal { get; set; }
        public int ReshteId { get; set; }
        public string ReshteName { get; set; }
        public int? Cnt { get; set; }
    }
}