// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Models.Common
{
    public partial class SP_StatusCntResult
    {
        public int Status { get; set; }
        public string StatusName { get; set; }
        public int? StatusCnt { get; set; }
    }
}
