// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fraud.Entities
{
    [Table("FireP23_CashPrmElh", Schema = "fr")]
    public partial class FireP23CashPrmElh
    {
        public int Id { get; set; }
        public int PrmSrdId { get; set; }
        public int? Op { get; set; }
        public int? Ebdid { get; set; }
        public int? MaliBid { get; set; }
        public int PolicyId { get; set; }
        public int? Bno { get; set; }
        public int ElhNo { get; set; }
        public string BnSodurDate { get; set; }
        public DateTime? BnSodurDateMiladi { get; set; }
        public int ReshteId { get; set; }
        public string ReshteName { get; set; }
        public string BeginDate { get; set; }
        public DateTime? BeginDateMiladi { get; set; }
        public string EndDate { get; set; }
        public DateTime? EndDateMiladi { get; set; }
        public int AgentId { get; set; }
        public string AgentName { get; set; }
        public int SodurId { get; set; }
        public string SodurName { get; set; }
        public int? BranchId { get; set; }
        public string BranchName { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public decimal? VosulShode { get; set; }
        public decimal? Remain { get; set; }
        public decimal PrmAsRial { get; set; }
        public string OperationType { get; set; }
        public string CreditType { get; set; }
        public string Comment { get; set; }
        public int Status { get; set; }
        public DateTime CreateDate { get; set; }
    }
}